// Inbyggd växtguide. Värdena är riktvärden för inomhusväxter under växtsäsong.
window.PLANT_LIBRARY = [
  { species: "Monstera (Monstera deliciosa)", water: 7, feed: 14, light: "ljust",
    tips: "Låt översta jordlagret torka mellan vattningarna. Torka av bladen ibland." },
  { species: "Gullranka (Epipremnum aureum)", water: 7, feed: 30, light: "halvskugga",
    tips: "Tålig och lättskött. Hängiga blad betyder att den är törstig." },
  { species: "Svärmors tunga (Dracaena trifasciata)", water: 21, feed: 60, light: "halvskugga",
    tips: "Vattna sparsamt, särskilt på vintern. Övervattning är den vanligaste dödsorsaken." },
  { species: "Zamioculcas (Zamioculcas zamiifolia)", water: 21, feed: 60, light: "halvskugga",
    tips: "Klarar torka och lite ljus. Låt jorden torka helt mellan vattningarna." },
  { species: "Fredskalla (Spathiphyllum)", water: 5, feed: 14, light: "halvskugga",
    tips: "Vill ha jämnt fuktig jord. Slokar tydligt när den behöver vatten." },
  { species: "Elefantöra (Alocasia)", water: 5, feed: 14, light: "ljust",
    tips: "Gillar hög luftfuktighet och jämn fukt, men inte stående vatten." },
  { species: "Fikus lyrata (Ficus lyrata)", water: 7, feed: 14, light: "ljust",
    tips: "Ogillar att flyttas och drag. Vattna när översta 3 cm är torra." },
  { species: "Benjaminfikus (Ficus benjamina)", water: 7, feed: 14, light: "ljust",
    tips: "Kan tappa blad vid flytt eller drag – den återhämtar sig oftast." },
  { species: "Gummifikus (Ficus elastica)", water: 10, feed: 30, light: "ljust",
    tips: "Torka av de stora bladen så att de kan ta upp ljus." },
  { species: "Hjärtformad filodendron (Philodendron hederaceum)", water: 7, feed: 30, light: "halvskugga",
    tips: "Lättskött klätterväxt. Gula blad kan tyda på för mycket vatten." },
  { species: "Ampellilja (Chlorophytum comosum)", water: 7, feed: 30, light: "ljust",
    tips: "Bildar små plantor som enkelt kan planteras om." },
  { species: "Aloe vera", water: 21, feed: 90, light: "sol",
    tips: "Suckulent. Vattna ordentligt men sällan, och låt jorden torka helt." },
  { species: "Kaktus (Cactaceae)", water: 28, feed: 90, light: "sol",
    tips: "Nästan ingen vattning under vintern. Behöver mycket ljus." },
  { species: "Suckulent (Echeveria m.fl.)", water: 14, feed: 60, light: "sol",
    tips: "Vattna när bladen känns lite mjuka. Använd dränerande jord." },
  { species: "Orkidé (Phalaenopsis)", water: 7, feed: 14, light: "ljust",
    tips: "Doppa krukan i vatten 10 minuter och låt rinna av. Rötterna ska vara silvriga innan nästa vattning." },
  { species: "Kalanchoe (Kalanchoe blossfeldiana)", water: 10, feed: 30, light: "sol",
    tips: "Suckulent som blommar. Undvik vatten på bladen." },
  { species: "Pilea (Pilea peperomioides)", water: 7, feed: 30, light: "ljust",
    tips: "Vrid krukan regelbundet så att den växer jämnt." },
  { species: "Kentiapalm (Howea forsteriana)", water: 7, feed: 30, light: "halvskugga",
    tips: "Jämnt fuktig jord. Bruna bladspetsar tyder på torr luft." },
  { species: "Murgröna (Hedera helix)", water: 5, feed: 14, light: "halvskugga",
    tips: "Gillar svalt. Håll utkik efter spinnkvalster om luften är torr." },
  { species: "Basilika (Ocimum basilicum)", water: 2, feed: 14, light: "sol",
    tips: "Vattna underifrån. Nyp av toppskotten så blir plantan buskigare." },
  { species: "Pelargon (Pelargonium)", water: 5, feed: 14, light: "sol",
    tips: "Låt jorden torka lätt mellan vattningarna. Ta bort vissna blommor." },
  { species: "Kaffeplanta (Coffea arabica)", water: 5, feed: 14, light: "ljust",
    tips: "Jämnt fuktig jord och hög luftfuktighet. Tål inte drag." }
];
